import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ReduxProvider } from "@/app/ReduxProvider";
import { AlertProvider } from "@/context/AlertContext";
import SessionSync from "@/components/sessionSync";
import Navigation from "@/app/navigation/navigation";
import "./globals.css";
import './globals.css';
import AuthProvider from "@/app/sessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        <ReduxProvider>
          <AlertProvider>
            <SessionSync />
            <Navigation />
            <main>{children}</main>
          </AlertProvider>
        </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
